;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.11
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :sodium)



(cffi:defcfun ("sodium_init" #.(lispify "sodium_init" 'function)) :int)

(cffi:defcfun ("crypto_auth_bytes" #.(lispify "crypto_auth_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_auth_keybytes" #.(lispify "crypto_auth_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_auth_PRIMITIVE" 'constant) "hmacsha512256")

(cffi:defcfun ("crypto_auth_primitive" #.(lispify "crypto_auth_primitive" 'function)) :string)

(cffi:defcfun ("crypto_auth" #.(lispify "crypto_auth" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_auth_verify" #.(lispify "crypto_auth_verify" 'function)) :int
  (h :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcstruct #.(lispify "crypto_auth_hmacsha256_state" 'classname)
	(#.(lispify "ictx" 'slotname) :pointer)
	(#.(lispify "octx" 'slotname) :pointer))

(cl:defconstant #.(lispify "crypto_auth_hmacsha256_BYTES" 'constant) 32)

(cffi:defcfun ("crypto_auth_hmacsha256_bytes" #.(lispify "crypto_auth_hmacsha256_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_auth_hmacsha256_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_auth_hmacsha256_keybytes" #.(lispify "crypto_auth_hmacsha256_keybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_auth_hmacsha256" #.(lispify "crypto_auth_hmacsha256" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_auth_hmacsha256_verify" #.(lispify "crypto_auth_hmacsha256_verify" 'function)) :int
  (h :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_auth_hmacsha256_init" #.(lispify "crypto_auth_hmacsha256_init" 'function)) :int
  (state :pointer)
  (key :pointer)
  (keylen :pointer))

(cffi:defcfun ("crypto_auth_hmacsha256_update" #.(lispify "crypto_auth_hmacsha256_update" 'function)) :int
  (state :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_auth_hmacsha256_final" #.(lispify "crypto_auth_hmacsha256_final" 'function)) :int
  (state :pointer)
  (out :pointer))

(cffi:defcstruct #.(lispify "crypto_auth_hmacsha512_state" 'classname)
	(#.(lispify "ictx" 'slotname) :pointer)
	(#.(lispify "octx" 'slotname) :pointer))

(cl:defconstant #.(lispify "crypto_auth_hmacsha512_BYTES" 'constant) 64)

(cffi:defcfun ("crypto_auth_hmacsha512_bytes" #.(lispify "crypto_auth_hmacsha512_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_auth_hmacsha512_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_auth_hmacsha512_keybytes" #.(lispify "crypto_auth_hmacsha512_keybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_auth_hmacsha512" #.(lispify "crypto_auth_hmacsha512" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_auth_hmacsha512_verify" #.(lispify "crypto_auth_hmacsha512_verify" 'function)) :int
  (h :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_auth_hmacsha512_init" #.(lispify "crypto_auth_hmacsha512_init" 'function)) :int
  (state :pointer)
  (key :pointer)
  (keylen :pointer))

(cffi:defcfun ("crypto_auth_hmacsha512_update" #.(lispify "crypto_auth_hmacsha512_update" 'function)) :int
  (state :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_auth_hmacsha512_final" #.(lispify "crypto_auth_hmacsha512_final" 'function)) :int
  (state :pointer)
  (out :pointer))

(cl:defconstant #.(lispify "crypto_auth_hmacsha512256_BYTES" 'constant) 32)

(cffi:defcfun ("crypto_auth_hmacsha512256_bytes" #.(lispify "crypto_auth_hmacsha512256_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_auth_hmacsha512256_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_auth_hmacsha512256_keybytes" #.(lispify "crypto_auth_hmacsha512256_keybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_auth_hmacsha512256" #.(lispify "crypto_auth_hmacsha512256" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_auth_hmacsha512256_verify" #.(lispify "crypto_auth_hmacsha512256_verify" 'function)) :int
  (h :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_auth_hmacsha512256_init" #.(lispify "crypto_auth_hmacsha512256_init" 'function)) :int
  (state :pointer)
  (key :pointer)
  (keylen :pointer))

(cffi:defcfun ("crypto_auth_hmacsha512256_update" #.(lispify "crypto_auth_hmacsha512256_update" 'function)) :int
  (state :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_auth_hmacsha512256_final" #.(lispify "crypto_auth_hmacsha512256_final" 'function)) :int
  (state :pointer)
  (out :pointer))

(cffi:defcfun ("crypto_box_publickeybytes" #.(lispify "crypto_box_publickeybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_box_secretkeybytes" #.(lispify "crypto_box_secretkeybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_box_beforenmbytes" #.(lispify "crypto_box_beforenmbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_box_noncebytes" #.(lispify "crypto_box_noncebytes" 'function)) :pointer)

(cffi:defcfun ("crypto_box_zerobytes" #.(lispify "crypto_box_zerobytes" 'function)) :pointer)

(cffi:defcfun ("crypto_box_boxzerobytes" #.(lispify "crypto_box_boxzerobytes" 'function)) :pointer)

(cffi:defcfun ("crypto_box_macbytes" #.(lispify "crypto_box_macbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_box_PRIMITIVE" 'constant) "curve25519xsalsa20poly1305")

(cffi:defcfun ("crypto_box_primitive" #.(lispify "crypto_box_primitive" 'function)) :string)

(cffi:defcfun ("crypto_box_keypair" #.(lispify "crypto_box_keypair" 'function)) :int
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_beforenm" #.(lispify "crypto_box_beforenm" 'function)) :int
  (k :pointer)
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_afternm" #.(lispify "crypto_box_afternm" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_box_open_afternm" #.(lispify "crypto_box_open_afternm" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_box" #.(lispify "crypto_box" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_open" #.(lispify "crypto_box_open" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_easy" #.(lispify "crypto_box_easy" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_open_easy" #.(lispify "crypto_box_open_easy" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (pk :pointer)
  (sk :pointer))

(cl:defconstant #.(lispify "crypto_box_curve25519xsalsa20poly1305_PUBLICKEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_publickeybytes" #.(lispify "crypto_box_curve25519xsalsa20poly1305_publickeybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_box_curve25519xsalsa20poly1305_SECRETKEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_secretkeybytes" #.(lispify "crypto_box_curve25519xsalsa20poly1305_secretkeybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_box_curve25519xsalsa20poly1305_BEFORENMBYTES" 'constant) 32)

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_beforenmbytes" #.(lispify "crypto_box_curve25519xsalsa20poly1305_beforenmbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_box_curve25519xsalsa20poly1305_NONCEBYTES" 'constant) 24)

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_noncebytes" #.(lispify "crypto_box_curve25519xsalsa20poly1305_noncebytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_box_curve25519xsalsa20poly1305_ZEROBYTES" 'constant) 32)

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_zerobytes" #.(lispify "crypto_box_curve25519xsalsa20poly1305_zerobytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_box_curve25519xsalsa20poly1305_BOXZEROBYTES" 'constant) 16)

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_boxzerobytes" #.(lispify "crypto_box_curve25519xsalsa20poly1305_boxzerobytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_box_curve25519xsalsa20poly1305_MACBYTES" 'constant) (cl:- 32 16))

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_macbytes" #.(lispify "crypto_box_curve25519xsalsa20poly1305_macbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305" #.(lispify "crypto_box_curve25519xsalsa20poly1305" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_open" #.(lispify "crypto_box_curve25519xsalsa20poly1305_open" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_keypair" #.(lispify "crypto_box_curve25519xsalsa20poly1305_keypair" 'function)) :int
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_beforenm" #.(lispify "crypto_box_curve25519xsalsa20poly1305_beforenm" 'function)) :int
  (k :pointer)
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_afternm" #.(lispify "crypto_box_curve25519xsalsa20poly1305_afternm" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_box_curve25519xsalsa20poly1305_open_afternm" #.(lispify "crypto_box_curve25519xsalsa20poly1305_open_afternm" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_core_hsalsa20_OUTPUTBYTES" 'constant) 32)

(cffi:defcfun ("crypto_core_hsalsa20_outputbytes" #.(lispify "crypto_core_hsalsa20_outputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_hsalsa20_INPUTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_hsalsa20_inputbytes" #.(lispify "crypto_core_hsalsa20_inputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_hsalsa20_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_core_hsalsa20_keybytes" #.(lispify "crypto_core_hsalsa20_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_hsalsa20_CONSTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_hsalsa20_constbytes" #.(lispify "crypto_core_hsalsa20_constbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_core_hsalsa20" #.(lispify "crypto_core_hsalsa20" 'function)) :int
  (out :pointer)
  (in :pointer)
  (k :pointer)
  (c :pointer))

(cl:defconstant #.(lispify "crypto_core_salsa20_OUTPUTBYTES" 'constant) 64)

(cffi:defcfun ("crypto_core_salsa20_outputbytes" #.(lispify "crypto_core_salsa20_outputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa20_INPUTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_salsa20_inputbytes" #.(lispify "crypto_core_salsa20_inputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa20_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_core_salsa20_keybytes" #.(lispify "crypto_core_salsa20_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa20_CONSTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_salsa20_constbytes" #.(lispify "crypto_core_salsa20_constbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_core_salsa20" #.(lispify "crypto_core_salsa20" 'function)) :int
  (out :pointer)
  (in :pointer)
  (k :pointer)
  (c :pointer))

(cl:defconstant #.(lispify "crypto_core_salsa2012_OUTPUTBYTES" 'constant) 64)

(cffi:defcfun ("crypto_core_salsa2012_outputbytes" #.(lispify "crypto_core_salsa2012_outputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa2012_INPUTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_salsa2012_inputbytes" #.(lispify "crypto_core_salsa2012_inputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa2012_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_core_salsa2012_keybytes" #.(lispify "crypto_core_salsa2012_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa2012_CONSTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_salsa2012_constbytes" #.(lispify "crypto_core_salsa2012_constbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_core_salsa2012" #.(lispify "crypto_core_salsa2012" 'function)) :int
  (out :pointer)
  (in :pointer)
  (k :pointer)
  (c :pointer))

(cl:defconstant #.(lispify "crypto_core_salsa208_OUTPUTBYTES" 'constant) 64)

(cffi:defcfun ("crypto_core_salsa208_outputbytes" #.(lispify "crypto_core_salsa208_outputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa208_INPUTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_salsa208_inputbytes" #.(lispify "crypto_core_salsa208_inputbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa208_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_core_salsa208_keybytes" #.(lispify "crypto_core_salsa208_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_core_salsa208_CONSTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_core_salsa208_constbytes" #.(lispify "crypto_core_salsa208_constbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_core_salsa208" #.(lispify "crypto_core_salsa208" 'function)) :int
  (out :pointer)
  (in :pointer)
  (k :pointer)
  (c :pointer))

(cffi:defcfun ("crypto_generichash_bytes_min" #.(lispify "crypto_generichash_bytes_min" 'function)) :pointer)

(cffi:defcfun ("crypto_generichash_bytes_max" #.(lispify "crypto_generichash_bytes_max" 'function)) :pointer)

(cffi:defcfun ("crypto_generichash_bytes" #.(lispify "crypto_generichash_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_generichash_keybytes_min" #.(lispify "crypto_generichash_keybytes_min" 'function)) :pointer)

(cffi:defcfun ("crypto_generichash_keybytes_max" #.(lispify "crypto_generichash_keybytes_max" 'function)) :pointer)

(cffi:defcfun ("crypto_generichash_keybytes" #.(lispify "crypto_generichash_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_PRIMITIVE" 'constant) "blake2b")

(cffi:defcfun ("crypto_generichash_primitive" #.(lispify "crypto_generichash_primitive" 'function)) :string)

(cffi:defcfun ("crypto_generichash" #.(lispify "crypto_generichash" 'function)) :int
  (out :pointer)
  (outlen :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (key :pointer)
  (keylen :pointer))

(cffi:defcfun ("crypto_generichash_init" #.(lispify "crypto_generichash_init" 'function)) :int
  (state :pointer)
  (key :pointer)
  (keylen :pointer)
  (outlen :pointer))

(cffi:defcfun ("crypto_generichash_update" #.(lispify "crypto_generichash_update" 'function)) :int
  (state :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_generichash_final" #.(lispify "crypto_generichash_final" 'function)) :int
  (state :pointer)
  (out :pointer)
  (outlen :pointer))

(cffi:defcstruct #.(lispify "crypto_generichash_blake2b_state" 'classname)
	(#.(lispify "h" 'slotname) :pointer)
	(#.(lispify "t" 'slotname) :pointer)
	(#.(lispify "f" 'slotname) :pointer)
	(#.(lispify "buf" 'slotname) :pointer)
	(#.(lispify "buflen" 'slotname) :pointer)
	(#.(lispify "last_node" 'slotname) :pointer))

(cl:defconstant #.(lispify "crypto_generichash_blake2b_BYTES_MIN" 'constant) 16)

(cffi:defcfun ("crypto_generichash_blake2b_bytes_min" #.(lispify "crypto_generichash_blake2b_bytes_min" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_blake2b_BYTES_MAX" 'constant) 64)

(cffi:defcfun ("crypto_generichash_blake2b_bytes_max" #.(lispify "crypto_generichash_blake2b_bytes_max" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_blake2b_BYTES" 'constant) 32)

(cffi:defcfun ("crypto_generichash_blake2b_bytes" #.(lispify "crypto_generichash_blake2b_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_blake2b_KEYBYTES_MIN" 'constant) 16)

(cffi:defcfun ("crypto_generichash_blake2b_keybytes_min" #.(lispify "crypto_generichash_blake2b_keybytes_min" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_blake2b_KEYBYTES_MAX" 'constant) 64)

(cffi:defcfun ("crypto_generichash_blake2b_keybytes_max" #.(lispify "crypto_generichash_blake2b_keybytes_max" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_blake2b_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_generichash_blake2b_keybytes" #.(lispify "crypto_generichash_blake2b_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_blake2b_SALTBYTES" 'constant) 16)

(cffi:defcfun ("crypto_generichash_blake2b_saltbytes" #.(lispify "crypto_generichash_blake2b_saltbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_generichash_blake2b_PERSONALBYTES" 'constant) 16)

(cffi:defcfun ("crypto_generichash_blake2b_personalbytes" #.(lispify "crypto_generichash_blake2b_personalbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_generichash_blake2b" #.(lispify "crypto_generichash_blake2b" 'function)) :int
  (out :pointer)
  (outlen :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (key :pointer)
  (keylen :pointer))

(cffi:defcfun ("crypto_generichash_blake2b_salt_personal" #.(lispify "crypto_generichash_blake2b_salt_personal" 'function)) :int
  (out :pointer)
  (outlen :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (key :pointer)
  (keylen :pointer)
  (salt :pointer)
  (personal :pointer))

(cffi:defcfun ("crypto_generichash_blake2b_init" #.(lispify "crypto_generichash_blake2b_init" 'function)) :int
  (state :pointer)
  (key :pointer)
  (keylen :pointer)
  (outlen :pointer))

(cffi:defcfun ("crypto_generichash_blake2b_init_salt_personal" #.(lispify "crypto_generichash_blake2b_init_salt_personal" 'function)) :int
  (state :pointer)
  (key :pointer)
  (keylen :pointer)
  (outlen :pointer)
  (salt :pointer)
  (personal :pointer))

(cffi:defcfun ("crypto_generichash_blake2b_update" #.(lispify "crypto_generichash_blake2b_update" 'function)) :int
  (state :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_generichash_blake2b_final" #.(lispify "crypto_generichash_blake2b_final" 'function)) :int
  (state :pointer)
  (out :pointer)
  (outlen :pointer))

(cffi:defcfun ("crypto_hash_bytes" #.(lispify "crypto_hash_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_hash" #.(lispify "crypto_hash" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cl:defconstant #.(lispify "crypto_hash_PRIMITIVE" 'constant) "sha512")

(cffi:defcfun ("crypto_hash_primitive" #.(lispify "crypto_hash_primitive" 'function)) :string)

(cffi:defcstruct #.(lispify "crypto_hash_sha256_state" 'classname)
	(#.(lispify "state" 'slotname) :pointer)
	(#.(lispify "count" 'slotname) :pointer)
	(#.(lispify "buf" 'slotname) :pointer))

(cl:defconstant #.(lispify "crypto_hash_sha256_BYTES" 'constant) 32)

(cffi:defcfun ("crypto_hash_sha256_bytes" #.(lispify "crypto_hash_sha256_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_hash_sha256" #.(lispify "crypto_hash_sha256" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_hash_sha256_init" #.(lispify "crypto_hash_sha256_init" 'function)) :int
  (state :pointer))

(cffi:defcfun ("crypto_hash_sha256_update" #.(lispify "crypto_hash_sha256_update" 'function)) :int
  (state :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_hash_sha256_final" #.(lispify "crypto_hash_sha256_final" 'function)) :int
  (state :pointer)
  (out :pointer))

(cffi:defcstruct #.(lispify "crypto_hash_sha512_state" 'classname)
	(#.(lispify "state" 'slotname) :pointer)
	(#.(lispify "count" 'slotname) :pointer)
	(#.(lispify "buf" 'slotname) :pointer))

(cl:defconstant #.(lispify "crypto_hash_sha512_BYTES" 'constant) 64)

(cffi:defcfun ("crypto_hash_sha512_bytes" #.(lispify "crypto_hash_sha512_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_hash_sha512" #.(lispify "crypto_hash_sha512" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_hash_sha512_init" #.(lispify "crypto_hash_sha512_init" 'function)) :int
  (state :pointer))

(cffi:defcfun ("crypto_hash_sha512_update" #.(lispify "crypto_hash_sha512_update" 'function)) :int
  (state :pointer)
  (in :pointer)
  (inlen :unsigned-long-long))

(cffi:defcfun ("crypto_hash_sha512_final" #.(lispify "crypto_hash_sha512_final" 'function)) :int
  (state :pointer)
  (out :pointer))

(cffi:defcfun ("crypto_onetimeauth_bytes" #.(lispify "crypto_onetimeauth_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_onetimeauth_keybytes" #.(lispify "crypto_onetimeauth_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_onetimeauth_PRIMITIVE" 'constant) "poly1305")

(cffi:defcfun ("crypto_onetimeauth_primitive" #.(lispify "crypto_onetimeauth_primitive" 'function)) :string)

(cffi:defcfun ("crypto_onetimeauth" #.(lispify "crypto_onetimeauth" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_onetimeauth_verify" #.(lispify "crypto_onetimeauth_verify" 'function)) :int
  (h :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcstruct #.(lispify "crypto_onetimeauth_poly1305_implementation" 'classname)
	(#.(lispify "implementation_name" 'slotname) :pointer)
	(#.(lispify "onetimeauth" 'slotname) :pointer)
	(#.(lispify "onetimeauth_verify" 'slotname) :pointer))

(cl:defconstant #.(lispify "crypto_onetimeauth_poly1305_BYTES" 'constant) 16)

(cffi:defcfun ("crypto_onetimeauth_poly1305_bytes" #.(lispify "crypto_onetimeauth_poly1305_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_onetimeauth_poly1305_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_onetimeauth_poly1305_keybytes" #.(lispify "crypto_onetimeauth_poly1305_keybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_onetimeauth_poly1305_implementation_name" #.(lispify "crypto_onetimeauth_poly1305_implementation_name" 'function)) :string)

(cffi:defcfun ("crypto_onetimeauth_poly1305_set_implementation" #.(lispify "crypto_onetimeauth_poly1305_set_implementation" 'function)) :int
  (impl :pointer))

(cffi:defcfun ("crypto_onetimeauth_pick_best_implementation" #.(lispify "crypto_onetimeauth_pick_best_implementation" 'function)) :pointer)

(cffi:defcfun ("crypto_onetimeauth_poly1305" #.(lispify "crypto_onetimeauth_poly1305" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_onetimeauth_poly1305_verify" #.(lispify "crypto_onetimeauth_poly1305_verify" 'function)) :int
  (h :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_pwhash_scryptsalsa208sha256_SALTBYTES" 'constant) 32)

(cffi:defcfun ("crypto_pwhash_scryptsalsa208sha256_saltbytes" #.(lispify "crypto_pwhash_scryptsalsa208sha256_saltbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_pwhash_scryptsalsa208sha256_STRBYTES" 'constant) 102)

(cffi:defcfun ("crypto_pwhash_scryptsalsa208sha256_strbytes" #.(lispify "crypto_pwhash_scryptsalsa208sha256_strbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_pwhash_scryptsalsa208sha256" #.(lispify "crypto_pwhash_scryptsalsa208sha256" 'function)) :int
  (out :pointer)
  (outlen :unsigned-long-long)
  (passwd :string)
  (passwdlen :unsigned-long-long)
  (salt :pointer)
  (opslimit :unsigned-long-long)
  (memlimit :pointer))

(cffi:defcfun ("crypto_pwhash_scryptsalsa208sha256_str" #.(lispify "crypto_pwhash_scryptsalsa208sha256_str" 'function)) :int
  (out :pointer)
  (passwd :string)
  (passwdlen :unsigned-long-long)
  (opslimit :unsigned-long-long)
  (memlimit :pointer))

(cffi:defcfun ("crypto_pwhash_scryptsalsa208sha256_str_verify" #.(lispify "crypto_pwhash_scryptsalsa208sha256_str_verify" 'function)) :int
  (str :pointer)
  (passwd :string)
  (passwdlen :unsigned-long-long))

(cl:defconstant #.(lispify "crypto_pwhash_scryptxsalsa208sha256_SALTBYTES" 'constant) 32)

(cl:defconstant #.(lispify "crypto_pwhash_scryptxsalsa208sha256_STRBYTES" 'constant) 102)

(cffi:defcfun ("crypto_scalarmult_bytes" #.(lispify "crypto_scalarmult_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_scalarmult_scalarbytes" #.(lispify "crypto_scalarmult_scalarbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_scalarmult_PRIMITIVE" 'constant) "curve25519")

(cffi:defcfun ("crypto_scalarmult_primitive" #.(lispify "crypto_scalarmult_primitive" 'function)) :string)

(cffi:defcfun ("crypto_scalarmult_base" #.(lispify "crypto_scalarmult_base" 'function)) :int
  (q :pointer)
  (n :pointer))

(cffi:defcfun ("crypto_scalarmult" #.(lispify "crypto_scalarmult" 'function)) :int
  (q :pointer)
  (n :pointer)
  (p :pointer))

(cl:defconstant #.(lispify "crypto_scalarmult_curve25519_BYTES" 'constant) 32)

(cffi:defcfun ("crypto_scalarmult_curve25519_bytes" #.(lispify "crypto_scalarmult_curve25519_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_scalarmult_curve25519_SCALARBYTES" 'constant) 32)

(cffi:defcfun ("crypto_scalarmult_curve25519_scalarbytes" #.(lispify "crypto_scalarmult_curve25519_scalarbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_scalarmult_curve25519" #.(lispify "crypto_scalarmult_curve25519" 'function)) :int
  (q :pointer)
  (n :pointer)
  (p :pointer))

(cffi:defcfun ("crypto_scalarmult_curve25519_base" #.(lispify "crypto_scalarmult_curve25519_base" 'function)) :int
  (q :pointer)
  (n :pointer))

(cffi:defcfun ("crypto_secretbox_keybytes" #.(lispify "crypto_secretbox_keybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_secretbox_noncebytes" #.(lispify "crypto_secretbox_noncebytes" 'function)) :pointer)

(cffi:defcfun ("crypto_secretbox_zerobytes" #.(lispify "crypto_secretbox_zerobytes" 'function)) :pointer)

(cffi:defcfun ("crypto_secretbox_boxzerobytes" #.(lispify "crypto_secretbox_boxzerobytes" 'function)) :pointer)

(cffi:defcfun ("crypto_secretbox_macbytes" #.(lispify "crypto_secretbox_macbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_secretbox_PRIMITIVE" 'constant) "xsalsa20poly1305")

(cffi:defcfun ("crypto_secretbox_primitive" #.(lispify "crypto_secretbox_primitive" 'function)) :string)

(cffi:defcfun ("crypto_secretbox" #.(lispify "crypto_secretbox" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_secretbox_open" #.(lispify "crypto_secretbox_open" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_secretbox_easy" #.(lispify "crypto_secretbox_easy" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_secretbox_open_easy" #.(lispify "crypto_secretbox_open_easy" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_secretbox_xsalsa20poly1305_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_secretbox_xsalsa20poly1305_keybytes" #.(lispify "crypto_secretbox_xsalsa20poly1305_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_secretbox_xsalsa20poly1305_NONCEBYTES" 'constant) 24)

(cffi:defcfun ("crypto_secretbox_xsalsa20poly1305_noncebytes" #.(lispify "crypto_secretbox_xsalsa20poly1305_noncebytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_secretbox_xsalsa20poly1305_ZEROBYTES" 'constant) 32)

(cffi:defcfun ("crypto_secretbox_xsalsa20poly1305_zerobytes" #.(lispify "crypto_secretbox_xsalsa20poly1305_zerobytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_secretbox_xsalsa20poly1305_BOXZEROBYTES" 'constant) 16)

(cffi:defcfun ("crypto_secretbox_xsalsa20poly1305_boxzerobytes" #.(lispify "crypto_secretbox_xsalsa20poly1305_boxzerobytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_secretbox_xsalsa20poly1305_MACBYTES" 'constant) (cl:- 32 16))

(cffi:defcfun ("crypto_secretbox_xsalsa20poly1305_macbytes" #.(lispify "crypto_secretbox_xsalsa20poly1305_macbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_secretbox_xsalsa20poly1305" #.(lispify "crypto_secretbox_xsalsa20poly1305" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_secretbox_xsalsa20poly1305_open" #.(lispify "crypto_secretbox_xsalsa20poly1305_open" 'function)) :int
  (m :pointer)
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_shorthash_bytes" #.(lispify "crypto_shorthash_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_shorthash_keybytes" #.(lispify "crypto_shorthash_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_shorthash_PRIMITIVE" 'constant) "siphash24")

(cffi:defcfun ("crypto_shorthash_primitive" #.(lispify "crypto_shorthash_primitive" 'function)) :string)

(cffi:defcfun ("crypto_shorthash" #.(lispify "crypto_shorthash" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_shorthash_siphash24_BYTES" 'constant) 8)

(cffi:defcfun ("crypto_shorthash_siphash24_bytes" #.(lispify "crypto_shorthash_siphash24_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_shorthash_siphash24_KEYBYTES" 'constant) 16)

(cffi:defcfun ("crypto_shorthash_siphash24_keybytes" #.(lispify "crypto_shorthash_siphash24_keybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_shorthash_siphash24" #.(lispify "crypto_shorthash_siphash24" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (k :pointer))

(cffi:defcfun ("crypto_sign_bytes" #.(lispify "crypto_sign_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_sign_seedbytes" #.(lispify "crypto_sign_seedbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_sign_publickeybytes" #.(lispify "crypto_sign_publickeybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_sign_secretkeybytes" #.(lispify "crypto_sign_secretkeybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_sign_PRIMITIVE" 'constant) "ed25519")

(cffi:defcfun ("crypto_sign_primitive" #.(lispify "crypto_sign_primitive" 'function)) :string)

(cffi:defcfun ("crypto_sign_seed_keypair" #.(lispify "crypto_sign_seed_keypair" 'function)) :int
  (pk :pointer)
  (sk :pointer)
  (seed :pointer))

(cffi:defcfun ("crypto_sign_keypair" #.(lispify "crypto_sign_keypair" 'function)) :int
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_sign" #.(lispify "crypto_sign" 'function)) :int
  (sm :pointer)
  (smlen :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (sk :pointer))

(cffi:defcfun ("crypto_sign_open" #.(lispify "crypto_sign_open" 'function)) :int
  (m :pointer)
  (mlen :pointer)
  (sm :pointer)
  (smlen :unsigned-long-long)
  (pk :pointer))

(cl:defconstant #.(lispify "crypto_sign_ed25519_BYTES" 'constant) 64)

(cffi:defcfun ("crypto_sign_ed25519_bytes" #.(lispify "crypto_sign_ed25519_bytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_sign_ed25519_SEEDBYTES" 'constant) 32)

(cffi:defcfun ("crypto_sign_ed25519_seedbytes" #.(lispify "crypto_sign_ed25519_seedbytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_sign_ed25519_PUBLICKEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_sign_ed25519_publickeybytes" #.(lispify "crypto_sign_ed25519_publickeybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_sign_ed25519_SECRETKEYBYTES" 'constant) (cl:+ 32 32))

(cffi:defcfun ("crypto_sign_ed25519_secretkeybytes" #.(lispify "crypto_sign_ed25519_secretkeybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_sign_ed25519" #.(lispify "crypto_sign_ed25519" 'function)) :int
  (sm :pointer)
  (smlen :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (sk :pointer))

(cffi:defcfun ("crypto_sign_ed25519_open" #.(lispify "crypto_sign_ed25519_open" 'function)) :int
  (m :pointer)
  (mlen :pointer)
  (sm :pointer)
  (smlen :unsigned-long-long)
  (pk :pointer))

(cffi:defcfun ("crypto_sign_ed25519_keypair" #.(lispify "crypto_sign_ed25519_keypair" 'function)) :int
  (pk :pointer)
  (sk :pointer))

(cffi:defcfun ("crypto_sign_ed25519_seed_keypair" #.(lispify "crypto_sign_ed25519_seed_keypair" 'function)) :int
  (pk :pointer)
  (sk :pointer)
  (seed :pointer))

(cffi:defcfun ("crypto_stream_keybytes" #.(lispify "crypto_stream_keybytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_noncebytes" #.(lispify "crypto_stream_noncebytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_PRIMITIVE" 'constant) "xsalsa20")

(cffi:defcfun ("crypto_stream_primitive" #.(lispify "crypto_stream_primitive" 'function)) :string)

(cffi:defcfun ("crypto_stream" #.(lispify "crypto_stream" 'function)) :int
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_xor" #.(lispify "crypto_stream_xor" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_stream_aes128ctr_KEYBYTES" 'constant) 16)

(cffi:defcfun ("crypto_stream_aes128ctr_keybytes" #.(lispify "crypto_stream_aes128ctr_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_aes128ctr_NONCEBYTES" 'constant) 16)

(cffi:defcfun ("crypto_stream_aes128ctr_noncebytes" #.(lispify "crypto_stream_aes128ctr_noncebytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_aes128ctr_BEFORENMBYTES" 'constant) 1408)

(cffi:defcfun ("crypto_stream_aes128ctr_beforenmbytes" #.(lispify "crypto_stream_aes128ctr_beforenmbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_aes128ctr" #.(lispify "crypto_stream_aes128ctr" 'function)) :int
  (out :pointer)
  (outlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_aes128ctr_xor" #.(lispify "crypto_stream_aes128ctr_xor" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_aes128ctr_beforenm" #.(lispify "crypto_stream_aes128ctr_beforenm" 'function)) :int
  (c :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_aes128ctr_afternm" #.(lispify "crypto_stream_aes128ctr_afternm" 'function)) :int
  (out :pointer)
  (len :unsigned-long-long)
  (nonce :pointer)
  (c :pointer))

(cffi:defcfun ("crypto_stream_aes128ctr_xor_afternm" #.(lispify "crypto_stream_aes128ctr_xor_afternm" 'function)) :int
  (out :pointer)
  (in :pointer)
  (len :unsigned-long-long)
  (nonce :pointer)
  (c :pointer))

(cl:defconstant #.(lispify "crypto_stream_aes256estream_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_stream_aes256estream_keybytes" #.(lispify "crypto_stream_aes256estream_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_aes256estream_NONCEBYTES" 'constant) 16)

(cffi:defcfun ("crypto_stream_aes256estream_noncebytes" #.(lispify "crypto_stream_aes256estream_noncebytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_aes256estream_BEFORENMBYTES" 'constant) 276)

(cffi:defcfun ("crypto_stream_aes256estream_beforenmbytes" #.(lispify "crypto_stream_aes256estream_beforenmbytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_aes256estream" #.(lispify "crypto_stream_aes256estream" 'function)) :int
  (out :pointer)
  (len :unsigned-long-long)
  (nonce :pointer)
  (c :pointer))

(cffi:defcfun ("crypto_stream_aes256estream_xor" #.(lispify "crypto_stream_aes256estream_xor" 'function)) :int
  (out :pointer)
  (in :pointer)
  (inlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_aes256estream_beforenm" #.(lispify "crypto_stream_aes256estream_beforenm" 'function)) :int
  (c :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_aes256estream_afternm" #.(lispify "crypto_stream_aes256estream_afternm" 'function)) :int
  (out :pointer)
  (len :unsigned-long-long)
  (nonce :pointer)
  (c :pointer))

(cffi:defcfun ("crypto_stream_aes256estream_xor_afternm" #.(lispify "crypto_stream_aes256estream_xor_afternm" 'function)) :int
  (out :pointer)
  (in :pointer)
  (len :unsigned-long-long)
  (nonce :pointer)
  (c :pointer))

(cl:defconstant #.(lispify "crypto_stream_chacha20_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_stream_chacha20_keybytes" #.(lispify "crypto_stream_chacha20_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_chacha20_NONCEBYTES" 'constant) 8)

(cffi:defcfun ("crypto_stream_chacha20_noncebytes" #.(lispify "crypto_stream_chacha20_noncebytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_chacha20" #.(lispify "crypto_stream_chacha20" 'function)) :int
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_chacha20_xor" #.(lispify "crypto_stream_chacha20_xor" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_stream_salsa20_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_stream_salsa20_keybytes" #.(lispify "crypto_stream_salsa20_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_salsa20_NONCEBYTES" 'constant) 8)

(cffi:defcfun ("crypto_stream_salsa20_noncebytes" #.(lispify "crypto_stream_salsa20_noncebytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_salsa20" #.(lispify "crypto_stream_salsa20" 'function)) :int
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_salsa20_xor" #.(lispify "crypto_stream_salsa20_xor" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_stream_salsa2012_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_stream_salsa2012_keybytes" #.(lispify "crypto_stream_salsa2012_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_salsa2012_NONCEBYTES" 'constant) 8)

(cffi:defcfun ("crypto_stream_salsa2012_noncebytes" #.(lispify "crypto_stream_salsa2012_noncebytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_salsa2012" #.(lispify "crypto_stream_salsa2012" 'function)) :int
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_salsa2012_xor" #.(lispify "crypto_stream_salsa2012_xor" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_stream_salsa208_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_stream_salsa208_keybytes" #.(lispify "crypto_stream_salsa208_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_salsa208_NONCEBYTES" 'constant) 8)

(cffi:defcfun ("crypto_stream_salsa208_noncebytes" #.(lispify "crypto_stream_salsa208_noncebytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_salsa208" #.(lispify "crypto_stream_salsa208" 'function)) :int
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_salsa208_xor" #.(lispify "crypto_stream_salsa208_xor" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_stream_xsalsa20_KEYBYTES" 'constant) 32)

(cffi:defcfun ("crypto_stream_xsalsa20_keybytes" #.(lispify "crypto_stream_xsalsa20_keybytes" 'function)) :pointer)

(cl:defconstant #.(lispify "crypto_stream_xsalsa20_NONCEBYTES" 'constant) 24)

(cffi:defcfun ("crypto_stream_xsalsa20_noncebytes" #.(lispify "crypto_stream_xsalsa20_noncebytes" 'function)) :pointer)

(cffi:defcfun ("crypto_stream_xsalsa20" #.(lispify "crypto_stream_xsalsa20" 'function)) :int
  (c :pointer)
  (clen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cffi:defcfun ("crypto_stream_xsalsa20_xor" #.(lispify "crypto_stream_xsalsa20_xor" 'function)) :int
  (c :pointer)
  (m :pointer)
  (mlen :unsigned-long-long)
  (n :pointer)
  (k :pointer))

(cl:defconstant #.(lispify "crypto_verify_16_BYTES" 'constant) 16)

(cffi:defcfun ("crypto_verify_16_bytes" #.(lispify "crypto_verify_16_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_verify_16" #.(lispify "crypto_verify_16" 'function)) :int
  (x :pointer)
  (y :pointer))

(cl:defconstant #.(lispify "crypto_verify_32_BYTES" 'constant) 32)

(cffi:defcfun ("crypto_verify_32_bytes" #.(lispify "crypto_verify_32_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_verify_32" #.(lispify "crypto_verify_32" 'function)) :int
  (x :pointer)
  (y :pointer))

(cl:defconstant #.(lispify "crypto_verify_64_BYTES" 'constant) 64)

(cffi:defcfun ("crypto_verify_64_bytes" #.(lispify "crypto_verify_64_bytes" 'function)) :pointer)

(cffi:defcfun ("crypto_verify_64" #.(lispify "crypto_verify_64" 'function)) :int
  (x :pointer)
  (y :pointer))

(cffi:defcstruct #.(lispify "randombytes_implementation" 'classname)
	(#.(lispify "implementation_name" 'slotname) :pointer)
	(#.(lispify "random" 'slotname) :pointer)
	(#.(lispify "stir" 'slotname) :pointer)
	(#.(lispify "uniform" 'slotname) :pointer)
	(#.(lispify "buf" 'slotname) :pointer)
	(#.(lispify "close" 'slotname) :pointer))

(cffi:defcfun ("randombytes_set_implementation" #.(lispify "randombytes_set_implementation" 'function)) :int
  (impl :pointer))

(cffi:defcfun ("randombytes" #.(lispify "randombytes" 'function)) :void
  (buf :pointer)
  (buf_len :unsigned-long-long))

(cffi:defcfun ("randombytes_implementation_name" #.(lispify "randombytes_implementation_name" 'function)) :string)

(cffi:defcfun ("randombytes_random" #.(lispify "randombytes_random" 'function)) :pointer)

(cffi:defcfun ("randombytes_stir" #.(lispify "randombytes_stir" 'function)) :void)

(cffi:defcfun ("randombytes_uniform" #.(lispify "randombytes_uniform" 'function)) :pointer
  (upper_bound :pointer))

(cffi:defcfun ("randombytes_buf" #.(lispify "randombytes_buf" 'function)) :void
  (buf :pointer)
  (size :pointer))

(cffi:defcfun ("randombytes_close" #.(lispify "randombytes_close" 'function)) :int)

(cffi:defcvar ("randombytes_salsa20_implementation" #.(lispify "randombytes_salsa20_implementation" 'variable))
 #.(lispify "randombytes_implementation" 'classname))

(cffi:defcfun ("randombytes_salsa20_implementation_name" #.(lispify "randombytes_salsa20_implementation_name" 'function)) :string)

(cffi:defcfun ("randombytes_salsa20_random" #.(lispify "randombytes_salsa20_random" 'function)) :pointer)

(cffi:defcfun ("randombytes_salsa20_random_stir" #.(lispify "randombytes_salsa20_random_stir" 'function)) :void)

(cffi:defcfun ("randombytes_salsa20_random_uniform" #.(lispify "randombytes_salsa20_random_uniform" 'function)) :pointer
  (upper_bound :pointer))

(cffi:defcfun ("randombytes_salsa20_random_buf" #.(lispify "randombytes_salsa20_random_buf" 'function)) :void
  (buf :pointer)
  (size :pointer))

(cffi:defcfun ("randombytes_salsa20_random_close" #.(lispify "randombytes_salsa20_random_close" 'function)) :int)

(cffi:defcvar ("randombytes_sysrandom_implementation" #.(lispify "randombytes_sysrandom_implementation" 'variable))
 #.(lispify "randombytes_implementation" 'classname))

(cffi:defcfun ("randombytes_sysrandom_implementation_name" #.(lispify "randombytes_sysrandom_implementation_name" 'function)) :string)

(cffi:defcfun ("randombytes_sysrandom" #.(lispify "randombytes_sysrandom" 'function)) :pointer)

(cffi:defcfun ("randombytes_sysrandom_stir" #.(lispify "randombytes_sysrandom_stir" 'function)) :void)

(cffi:defcfun ("randombytes_sysrandom_uniform" #.(lispify "randombytes_sysrandom_uniform" 'function)) :pointer
  (upper_bound :pointer))

(cffi:defcfun ("randombytes_sysrandom_buf" #.(lispify "randombytes_sysrandom_buf" 'function)) :void
  (buf :pointer)
  (size :pointer))

(cffi:defcfun ("randombytes_sysrandom_close" #.(lispify "randombytes_sysrandom_close" 'function)) :int)

(cl:defconstant #.(lispify "__SODIUM_RUNTIME_H__" 'constant) 1)

(cffi:defcfun ("sodium_runtime_get_cpu_features" #.(lispify "sodium_runtime_get_cpu_features" 'function)) :int)

(cffi:defcfun ("sodium_runtime_has_neon" #.(lispify "sodium_runtime_has_neon" 'function)) :int)

(cffi:defcfun ("sodium_runtime_has_sse2" #.(lispify "sodium_runtime_has_sse2" 'function)) :int)

(cffi:defcfun ("sodium_runtime_has_sse3" #.(lispify "sodium_runtime_has_sse3" 'function)) :int)

(cffi:defcfun ("_sodium_alignedcalloc" #.(lispify "_sodium_alignedcalloc" 'function)) :pointer
  (unaligned_p :pointer)
  (len :pointer))

(cffi:defcfun ("sodium_memzero" #.(lispify "sodium_memzero" 'function)) :void
  (pnt :pointer)
  (len :pointer))

(cffi:defcfun ("sodium_memcmp" #.(lispify "sodium_memcmp" 'function)) :int
  (b1_ :pointer)
  (b2_ :pointer)
  (len :pointer))

(cffi:defcfun ("sodium_bin2hex" #.(lispify "sodium_bin2hex" 'function)) :string
  (hex :string)
  (hex_maxlen :pointer)
  (bin :pointer)
  (bin_len :pointer))

(cffi:defcfun ("sodium_hex2bin" #.(lispify "sodium_hex2bin" 'function)) :int
  (bin :pointer)
  (bin_maxlen :pointer)
  (hex :string)
  (hex_len :pointer)
  (ignore :string)
  (bin_len :pointer)
  (hex_end :pointer))

(cffi:defcfun ("sodium_mlock" #.(lispify "sodium_mlock" 'function)) :int
  (addr :pointer)
  (len :pointer))

(cffi:defcfun ("sodium_munlock" #.(lispify "sodium_munlock" 'function)) :int
  (addr :pointer)
  (len :pointer))

(cl:defconstant #.(lispify "SODIUM_VERSION_STRING" 'constant) "0.5.1")

(cl:defconstant #.(lispify "SODIUM_LIBRARY_VERSION_MAJOR" 'constant) 5)

(cl:defconstant #.(lispify "SODIUM_LIBRARY_VERSION_MINOR" 'constant) 1)

(cffi:defcfun ("sodium_version_string" #.(lispify "sodium_version_string" 'function)) :string)

(cffi:defcfun ("sodium_library_version_major" #.(lispify "sodium_library_version_major" 'function)) :int)

(cffi:defcfun ("sodium_library_version_minor" #.(lispify "sodium_library_version_minor" 'function)) :int)


