%module bindings

%feature("intern_function", "lispify");

%insert("lisphead") %{
(in-package :sodium)
%}

%include "path-to-sodium-headers/sodium/export.h"
%include "path-to-sodium-headers/sodium/core.h"
%include "path-to-sodium-headers/sodium/crypto_auth.h"
%include "path-to-sodium-headers/sodium/crypto_auth_hmacsha256.h"
%include "path-to-sodium-headers/sodium/crypto_auth_hmacsha512.h"
%include "path-to-sodium-headers/sodium/crypto_auth_hmacsha512256.h"
%include "path-to-sodium-headers/sodium/crypto_box.h"
%include "path-to-sodium-headers/sodium/crypto_box_curve25519xsalsa20poly1305.h"
%include "path-to-sodium-headers/sodium/crypto_core_hsalsa20.h"
%include "path-to-sodium-headers/sodium/crypto_core_salsa20.h"
%include "path-to-sodium-headers/sodium/crypto_core_salsa2012.h"
%include "path-to-sodium-headers/sodium/crypto_core_salsa208.h"
%include "path-to-sodium-headers/sodium/crypto_generichash.h"
%include "path-to-sodium-headers/sodium/crypto_generichash_blake2b.h"
%include "path-to-sodium-headers/sodium/crypto_hash.h"
%include "path-to-sodium-headers/sodium/crypto_hash_sha256.h"
%include "path-to-sodium-headers/sodium/crypto_hash_sha512.h"
%include "path-to-sodium-headers/sodium/crypto_onetimeauth.h"
%include "path-to-sodium-headers/sodium/crypto_onetimeauth_poly1305.h"
%include "path-to-sodium-headers/sodium/crypto_pwhash_scryptsalsa208sha256.h"
%include "path-to-sodium-headers/sodium/crypto_scalarmult.h"
%include "path-to-sodium-headers/sodium/crypto_scalarmult_curve25519.h"
%include "path-to-sodium-headers/sodium/crypto_secretbox.h"
%include "path-to-sodium-headers/sodium/crypto_secretbox_xsalsa20poly1305.h"
%include "path-to-sodium-headers/sodium/crypto_shorthash.h"
%include "path-to-sodium-headers/sodium/crypto_shorthash_siphash24.h"
%include "path-to-sodium-headers/sodium/crypto_sign.h"
%include "path-to-sodium-headers/sodium/crypto_sign_ed25519.h"
%include "path-to-sodium-headers/sodium/crypto_stream.h"
%include "path-to-sodium-headers/sodium/crypto_stream_aes128ctr.h"
%include "path-to-sodium-headers/sodium/crypto_stream_aes256estream.h"
%include "path-to-sodium-headers/sodium/crypto_stream_chacha20.h"
%include "path-to-sodium-headers/sodium/crypto_stream_salsa20.h"
%include "path-to-sodium-headers/sodium/crypto_stream_salsa2012.h"
%include "path-to-sodium-headers/sodium/crypto_stream_salsa208.h"
%include "path-to-sodium-headers/sodium/crypto_stream_xsalsa20.h"
%include "path-to-sodium-headers/sodium/crypto_verify_16.h"
%include "path-to-sodium-headers/sodium/crypto_verify_32.h"
%include "path-to-sodium-headers/sodium/crypto_verify_64.h"
%include "path-to-sodium-headers/sodium/randombytes.h"
%include "path-to-sodium-headers/sodium/randombytes_salsa20_random.h"
%include "path-to-sodium-headers/sodium/randombytes_sysrandom.h"
%include "path-to-sodium-headers/sodium/runtime.h"
%include "path-to-sodium-headers/sodium/utils.h"
%include "path-to-sodium-headers/sodium/version.h"

